name: Movie Checker

on:
  schedule:
    # Runs every 30 minutes (GitHub may delay scheduled jobs slightly)
    - cron: "7,37 * * * *"

  # Allows you to manually run it from GitHub Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_movies:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run movie checker
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python movie_checker.py

      - name: Save bot data
        run: |
          git config --global user.name "Movie-Man-Bot"
          git config --global user.email "movie-man-bot@github.com"

          git add watchlist.json telegram_offset.txt || true

          git commit -m "Update bot data" || exit 0

          git push
